security:
    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                property: apiKey
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$yGsDa0GH7of4ybn.bBXk7e4572aM/QiSNcbFbzyzq4RRE03NpF9aa
                        roles: 'ROLE_ADMIN'
        login_form_provider:
            entity:
                class: App\Entity\DcProfile
                property: username
        # in_memory: { memory: ~ }
    role_hierarchy:
            ROLE_ADMIN: [ROLE_API]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            provider: user_db_provider
        api1:
            pattern: ^/api
            http_basic: true
            provider: in_memory
        main:
            anonymous: ~
            provider: login_form_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
    access_control:
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
    encoders:
        Symfony\Component\Security\Core\User\User:
           algorithm: bcrypt
           cost: 12
